### ISSUE TITLE
CoinMessageHandler doesn't compile

### ISSUE THREAD

**Issue by wolfv** [coin-or/CoinUtils#1]
The code in this line doesn't compile for me (gcc, ubuntu 14.04).
`sprintf(messageOut_,format_+2);`

https://github.com/coin-or/CoinUtils/blob/master/CoinUtils/src/CoinMessageHandler.cpp#L834

I am getting the following error: CoinMessageHandler.cpp:834:35: error: format not a string literal and no format arguments

**Comment by tkralphs** [comment]
Hmm, seems this should ordinarily be a warning. Did you add a flag to make it an error? What is the gcc version? In general, CoinUtils seems to be building fine:

https://travis-ci.org/coin-or/CoinUtils

I suppose this should be fixed, but for now, you can try configuring with `ADD_CXXFLAGS=-Wno-error=format-security`.

**Comment by wolfv** [comment]
Hi @tkralphs 

I actually found a patch from 2 years ago here: https://lists.fedoraproject.org/pipermail/scm-commits/Week-of-Mon-20131216/1159884.html

Maybe it could be fixed upstream?

Wolf

**Comment by tkralphs** [comment]
This was now fixed. Thanks for the report!

**Comment by wolfv** [comment]
awesome, thanks a lot!
