### ISSUE TITLE
Global variables outside namespace

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#100]
In [`CoinMpsIO.cpp`](https://github.com/coin-or/CoinUtils/blob/master/CoinUtils/src/CoinMpsIO.cpp), there are a number of global variables declared, e.g.,
```
const static char *section[] = {
  "", "NAME", "ROW", "COLUMN", "RHS", "RANGES", "BOUNDS", "ENDATA", " ", "QSECTION", ...
};
```
I'm not sure why this is necessary, but at some point, it appears that someone put some of them into a namespace to make them file local, e.g.,
```
namespace {
const double fraction[] = { 1.0, 1.0e-1, 1.0e-2, 1.0e-3, 1.0e-4, 1.0e-5, 1.0e-6, 1.0e-7, 1.0e-8, ...
} // end file-local namespace
```
I discovered this because there was a variable name clash with a variable in some other code I was debugging. Any reason not to make the rest of the variables file local?

**Comment by h-g-s** [comment]
The "const static char *section" seems to be ok, it is read-only and only visible in the current file. 

I didn't understood why a namespace was used...

**Comment by tkralphs** [comment]
As it is right now, the variables declared outside `namespace` are global. To see what I mean, launch Cbc in `gdb` and `print section`. You will see it is defined and accessible even within Cbc, although it is defined in CounUtils. It's accessible to any code that links to `CoinUtils`. Putting it into a namespace limits its scope. An unnamed namespace limits the scope to just functions and classes in the same file (I guess "compilation unit," to be precise). 

The global variables can end up having the same names as local variables (this is what happened to me) and I guess that could cause problems. In this case, it seems not to, since the MPS reader is only invoked once at the beginning. I'm not sure what would happen if I assigned a new value to a local version of that variable and then tried to use the MPS reader after that. I suppose the `const` declaration prevents the global from being over-written or causing any problems, but it can be confusing when debugging, since the variable initially seems to have a value assigned from outside the code. Having global variables just seems to be bad style overall.

**Comment by svigerske** [comment]
Having the variable begin static should prevent clashes with functions or variables of the same name in other compilation units. Maybe gdb has a wider view, don't know.
Making it `const`, i.e. read-only, makes it a well-behaved "global" variable, in my opinion.
Also I saw somewhere a suggestion that `const static char*` is preferred over a `#define`.

Anyhow, there is no harm to put this into an unnamed namespace, too.

**Comment by tkralphs** [comment]
It is more than just `section`, there are others as well. I guess it would be good to be consistent.
