### ISSUE TITLE
Massive memory use in presolve

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/CoinUtils#103]
I have a ILP that uses ~10GB of memory as peak in presolving.
I use the master version.

Valgrind tells me:

->81.58% (8,546,583,736B) 0x4AB848: drop_zero_coefficients_action::presolve(CoinPresolveMatrix*, int*, int, CoinPresolveAction const*) (CoinPresolveZeros.cpp:247)
| ->81.58% (8,546,527,032B) 0x4DF09D: doubleton_action::presolve(CoinPresolveMatrix*, CoinPresolveAction const*) (CoinPresolveDoubleton.cpp:763)
| | ->81.58% (8,546,527,032B) 0x4A2899: ClpPresolve::presolve(CoinPresolveMatrix*) (ClpPresolve.cpp:1125)
| |   ->81.58% (8,546,527,032B) 0x4A7554: ClpPresolve::gutsOfPresolvedModel(ClpSimplex*, double, bool, int, bool, bool, char const*, char const*) (ClpPresolve.cpp:2276)
| |     ->81.58% (8,546,527,032B) 0x55DF37: ClpSimplex::initialSolve(ClpSolve&) (ClpSolve.cpp:975)
| |       ->81.58% (8,546,527,032B) 0x47C957: OsiClpSolverInterface::initialSolve() (OsiClpSolverInterface.cpp:731)
| |         ->81.58% (8,546,527,032B) 0x7FF68D: CbcModel::initialSolve() (CbcModel.cpp:5466)
| |           ->81.58% (8,546,527,032B) 0x64897B: CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) (CbcSolver.cpp:3757)
| |             ->81.58% (8,546,527,032B) 0x66E74A: CbcMain1(int, char const**, CbcModel&) (CbcSolver.cpp:1334)
| |               ->81.58% (8,546,527,032B) 0x40BBCC: solveLP(char const*) (clpsolve.cpp:142)
| |                 ->81.58% (8,546,527,032B) 0x3F67B6: main (main.cpp:163)

=> I have taken a look there:

That is the 

dropped_zero *zeros = new dropped_zero[nzeros];

line.

Actually, I think it is even worse, as the nzeros counter is a plain int and for my ILP it has already overflown, if I use e.g. a long long in the function computing this (count_col_zeros), the value is much higher (but I could be mistaken).

The ILP triggering that is around 80 MB of text, not sure how to share this best if there is interest in a closer review.

**Comment by christoph-cullmann** [comment]
Here the input lp as ZIP
[test.zip](https://github.com/coin-or/CoinUtils/files/3466576/test.zip)

**Comment by jjhforrest** [comment]
Will look at it.

**Comment by christoph-cullmann** [comment]
Thanks ;=)

I think the issue with this ILP is that we generate here massive

a - b = 0
b - c = 0
c - d = 0
....

chains.

I will try to improve our ILP generation, thought this seems to show some corner case that is not that optimally handles in the pre-solving.

**Comment by jjhforrest** [comment]
Christoph,

I think I have fixed - should mean that all problems may use a bit less 
memory.

In presolve if you find x - y = 0.0 then you get rid of x and do 
substitutions.  Some elements of y may have gone to zero so you add y to 
a list to check later.  Now you find z - y = 0.0 and get rid of z.  So y 
is added to list again.

In this case there were 160,000 on list but only 300 unique (when I 
tried).  And the code thought it had about a billion zero elements!

John

**Comment by christoph-cullmann** [comment]
Thanks!

I will try the new version.

I optimized away such long a = b = c = ... chains now in our ILP generator, too.
And yes, for the example I attached here, this remove 1049023 ILP variables from the generated ILP, it was highly redundant.

**Comment by christoph-cullmann** [comment]
Hmm, guess I need to test later, CBC master seems to be a bit broken ATM

/local/ssd/cullmann/build/lpsolve.clpsolve/libcbc/src/Cbc/src/CbcSolver.cpp:4007:35: error: use of undeclared identifier 'cgraph_density'

**Comment by christoph-cullmann** [comment]
I synced our local cbc clone to master, I can confirm that your fix works nicely.
Only 3GB of memory used as peak.

**Comment by svigerske** [comment]
Cherry-picked the fix from @jjhforrest to stable/2.11, so you don't have to use trunk/master just for that.
