### ISSUE TITLE
Visual Studio (2019) compile issues (64-bit)

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/CoinUtils#104]
There are some format string errors and missing includes.

See discussion on 
https://github.com/coin-or/Cbc/commit/e55f79bf1b03902c78ce92bc9126e09b93c21032

@h-g-s

**Comment by tkralphs** [comment]
If it's easy, can you open a PR with your proposed patch, then tests will be automatically run on all platforms.

**Comment by christoph-cullmann** [comment]
Can create a pull request, yes.

**Comment by christoph-cullmann** [comment]
Matching pull request https://github.com/coin-or/CoinUtils/pull/105

**Comment by tkralphs** [comment]
Closed by 7602c81

**Comment by tkralphs** [comment]
Closed by 7602c81

**Comment by christoph-cullmann** [comment]
Thanks!
Tested this now on our internal compile & test farm, all fine, cool!
