### ISSUE TITLE
Cannot build in mingw64 with intel compilers

### ISSUE THREAD

**Issue by fmaire16** [coin-or/CoinUtils#112]
Hi All,

I get a lot of error when trying to build coinutils (as part of cbc) with intel compilers (v19).
Note sure what to do about it

CoinAlloc.cpp
source='CoinBuild.cpp' object='CoinBuild.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
/bin/sh ../../libtool --tag=CXX --mode=compile icl -DHAVE_CONFIG_H -I. -I`echo .`     -MT -Ox -nologo -EHsc -GR -D_CRT_SECURE_NO_DEPRECATE -DNDEBUG    -DCOINUTILS_BUILD -c -o CoinBuild.lo CoinBuild.cpp
 icl -DHAVE_CONFIG_H -I. -I. -MT -Ox -nologo -EHsc -GR -D_CRT_SECURE_NO_DEPRECATE -DNDEBUG -DCOINUTILS_BUILD -c CoinBuild.cpp
CoinBuild.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(92): error: expected an identifier
          !_Is_implicitly_default_constructible<_Uty1>::value || !_Is_implicitly_default_constructible<_Uty2>::value)
          ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(91): error: not a valid member class or function template declaration
      constexpr explicit(
      ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(91): error: "explicit" is not allowed
      constexpr explicit(
      ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(93): error: expected a ";"
          pair() noexcept(
          ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(175): error: expected an identifier
      constexpr explicit(!is_convertible<const _Other1&, _Ty1>::value // TRANSITION, VSO#946746
                         ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(175): error: not a valid member class or function template declaration
      constexpr explicit(!is_convertible<const _Other1&, _Ty1>::value // TRANSITION, VSO#946746
      ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(175): error: "explicit" is not allowed
      constexpr explicit(!is_convertible<const _Other1&, _Ty1>::value // TRANSITION, VSO#946746
      ^

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\utility(177): error: expected a ";"
          pair(const pair<_Other1, _Other2>& _Right) noexcept(is_nothrow_constructible_v<_Ty1, const _Other1&>&&
          ^

compilation aborted for CoinBuild.cpp (code 2)
make[3]: *** [Makefile:725: CoinBuild.lo] Error 1
make[3]: Leaving directory '/c/Users/family/Documents/SolverCBC/3/coinutils/CoinUtils/src'
make[2]: *** [Makefile:540: all] Error 2
make[2]: Leaving directory '/c/Users/family/Documents/SolverCBC/3/coinutils/CoinUtils/src'
make[1]: *** [Makefile:436: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/family/Documents/SolverCBC/3/coinutils/CoinUtils'
make: *** [Makefile:323: all-recursive] Error 1

**Comment by fmaire16** [comment]
seems to be a visual studio 2019 bug - downgrading to vs 2017 this works...

**Comment by tkralphs** [comment]
I guess you meant Visual Studio compilers, not Intel? Maybe you could edit the title so it's not confusing to anyone who finds this later. 

In any case, Cbc is being built with Visual Studio 2019 and the build is currently going through, but perhaps this is an issue with a specific release of Visual Studio 2019. The error messages do look strange and point to some internal problem with Visual Studio itself. 

I'm going to close this for now, but feel free to re-open it if you have more information.

**Comment by fmaire16** [comment]
Thanks Ted - yes you can close the issue.
This happened only using the Intel compilers (XE 2019 version) with
Microsoft Visual Studio 2019 (both directly or through Mingw64 with the
--enable-msvc command). Using the Intel compilers with Microsoft Visual
Studio 2017 solved the issues...
