### ISSUE TITLE
rename conflict graph files

### ISSUE THREAD

**Issue by svigerske** [coin-or/CoinUtils#115]
Please rename files like bron_kerbosch.h, cgraph.h, ..., vint_set.h, to follow the naming-style of functions in CoinUtils.

This should happen before creating a new stable branch from the current master/trunk.

**Comment by h-g-s** [comment]
Hi @svigerske .  Yes, I and Samuel are working to reorganize the conflict graph related files to follow the naming style of CoinUtils. Samuel is also trying some additional optimizations lately.

**Comment by tkralphs** [comment]
This applies not only to CoinUtils, but to all related projects, especially Cbc. There are also other issues that I hope you can addresss, such as the lack of standard header information at the top of each file (indicating license, copyright, etc.).

**Comment by tkralphs** [comment]
This seems to be done now, at least in CoinUtils. @h-g-s am I correct?

**Comment by h-g-s** [comment]
Yes, we now merged in trunk the re-organized (and faster) conflict graph structure.
