### ISSUE TITLE
Update configure scripts

### ISSUE THREAD

**Issue by giordano** [coin-or/CoinUtils#117]
This is similar to https://github.com/coin-or-tools/ThirdParty-Blas/issues/1: could you please update the `configure` script and perhaps all the helper scripts to the latest version available?  For example I can't build the shared library for FreeBSD and PowerPC.

Also, it's impossible to run `autoreconf` because this package isn't self-contained and it doesn't ship the definitions of the M4 macros used in `configure.ac`.  I tried using https://github.com/coin-or-tools/BuildTools, as suggested in https://github.com/coin-or-tools/ThirdParty-Blas/issues/1, but in this case even after manually modifying `configure.ac` to add
```
AC_CONFIG_MACRO_DIRS([BuildTools])
```
I get the following errors:
```
autoreconf: Entering directory `CoinUtils'
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
configure.ac:44: error: possibly undefined macro: AC_COIN_PROJECTDIR_INIT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_COIN_DEBUG_COMPILE
configure.ac:50: error: possibly undefined macro: AC_COIN_PROG_CXX
configure.ac:53: error: possibly undefined macro: AC_COIN_PROG_F77
configure.ac:58: error: possibly undefined macro: AC_COIN_F77_WRAPPERS
configure.ac:62: error: possibly undefined macro: AC_COIN_INIT_AUTO_TOOLS
configure.ac:68: error: possibly undefined macro: AC_COIN_CHECK_ISFINITE
configure.ac:69: error: possibly undefined macro: AC_COIN_CHECK_ISNAN
configure.ac:125: error: possibly undefined macro: AC_COIN_CHECK_CXX_CHEADER
configure.ac:257: error: possibly undefined macro: AC_COIN_CHECK_LIBM
configure.ac:259: error: possibly undefined macro: AC_COIN_CHECK_PACKAGE_BLAS
configure.ac:260: error: possibly undefined macro: AC_COIN_CHECK_PACKAGE_LAPACK
configure.ac:261: error: possibly undefined macro: AC_COIN_CHECK_PACKAGE
configure.ac:265: error: possibly undefined macro: AC_COIN_CHECK_GNU_ZLIB
configure.ac:266: error: possibly undefined macro: AC_COIN_CHECK_GNU_BZLIB
configure.ac:267: error: possibly undefined macro: AC_COIN_CHECK_GNU_READLINE
configure.ac:269: error: possibly undefined macro: AC_COIN_VPATH_LINK
configure.ac:275: error: possibly undefined macro: AC_COIN_DOXYGEN
configure.ac:293: error: possibly undefined macro: AC_COIN_FINALIZE
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by svigerske** [comment]
The current master of CoinUtils has configure, etc., generated from quite recent autotools versions (autoconf 2.69, autoconf-archive 2019.01.06, automake 1.16.1, libtool 2.4.6), but we also need some additional patches.
At some point, there will also be a release from master.

The `stable/*`-branches and releases of CoinUtils use BuildTools branch stable/0.8, not master.

**Comment by giordano** [comment]
> autoconf 2.69

Are you sure? https://github.com/coin-or/CoinUtils/blob/f709081c9b57cc2dd32579d804b30689ca789982/configure#L4-L10  That's 17-year old.

For powerpc64le it still uses the wrong LD emulator https://github.com/coin-or/CoinUtils/blob/f709081c9b57cc2dd32579d804b30689ca789982/configure#L6429-L6431 it should be `elf64lppc`, at least I could manually patch this as this is a single line to fix.

For FreeBSD instead, `configure` forces not to build shared libraries in several places, like https://github.com/coin-or/CoinUtils/blob/f709081c9b57cc2dd32579d804b30689ca789982/configure#L9368-L9370 https://github.com/coin-or/CoinUtils/blob/f709081c9b57cc2dd32579d804b30689ca789982/configure#L9980-L9982 https://github.com/coin-or/CoinUtils/blob/f709081c9b57cc2dd32579d804b30689ca789982/configure#L13940-L13942 and so on.  Just regenerating the configure script with a really recent autoconf would solve all these issues, unfortunately it's not really simple for a non-maintainer to do this right.

> The stable/*-branches and releases of CoinUtils use BuildTools branch stable/0.8, not master.

That's what I'm using, as you suggested in https://github.com/coin-or-tools/ThirdParty-Blas/issues/1.  I could make it work for COINBLAS, not here.

I clearly don't know what I have to do to be able to run `autoreconf`, so would be glad if you could fix it for everyone.

**Comment by svigerske** [comment]
I'm sure that for **master** we use more recent autotools versions: https://github.com/coin-or/CoinUtils/blob/master/configure#L3  f709081c9 is the latest release (2.11.4).
As said, at some day, there will also be a release from master. But as some colleagues want to get some other (unrelated) work done first, it's not foreseeable to me when this will happen.

We cannot just run autoreconf on the last stable branch or last release, because the [patches we have for libtool](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1709), etc, will not apply. It took some years to update the whole buildsystem to work with recent autotools version (and add some features we were missing, too) - that was much more work than just running autoconf again.

**Comment by giordano** [comment]
Ok, it looks like I was looking at the last tagged version, even though I was pretty sure I was reading `configure` from `master`

**Comment by Neumann-A** [comment]
> We cannot just run autoreconf on the last stable branch or last release, because the [patches we have for libtool](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1709), etc, will not apply.

maybe you should have upstreamed those changes?
