### ISSUE TITLE
`configure` ignores `--with-lapack-lflags` and `--with-lapack-cflags` in its tests

### ISSUE THREAD

**Issue by giordano** [coin-or/CoinUtils#119]
Quoting from `./configure --help`:
```
$ ./configure --help
[...]
  --with-lapack           Use lapack. If an argument is given, 'yes' is
                          equivalent to --with-lapack, 'no' is
                          equivalent to --without-lapack. Any other argument
                          is applied as for --with-lapack-lflags
  --with-lapack-lflags    Linker flags for lapack appropriate for your
                          environment. (Most often, -l specs for libraries.)
  --with-lapack-cflags    Compiler flags for lapack appropriate for your
                          environment. (Most often, -I specs for header file
                          directories.)
[...]
```
but if I set `--with-lapack-lflags` and `--with-lapack-cflags`, the tests to check lapack ignore these flags...

I'd be happy to have a look if only I had an idea where the test macros come from (well, probably https://github.com/coin-or-tools/BuildTools/?) & I was able to run `autoreconf` locally (related to #117)...

**Comment by svigerske** [comment]
af8834ab26 adds some quotes that could have been missing when handling these flags.

I ran this version with `--with-lapack-lflags=-llapack` and get this in the configure output:
```
...
checking for pkgconf... pkgconf
checking pkgconf is at least version 0.16.0... yes: 1.6.3
configure: pkgconf path is "/***:"
checking for function dsyev_ in -llapack ... yes
checking for package Glpk... yes
...
```

So it seems to have been picked up on my system.

The idea is that https://github.com/coin-or/CoinUtils/blob/af8834ab26d37ac9a81fee6897a4de1c93e1ff13/configure#L18030-L18042 sets `coin_has_lapack=yes` and stores your flags in `lapack_lflags`.
https://github.com/coin-or/CoinUtils/blob/af8834ab26d37ac9a81fee6897a4de1c93e1ff13/configure#L18150-L18222 then check whether these flags work. There should be an error if they didn't work.

The m4 source is macro AC_COIN_CHK_LAPACK at https://github.com/coin-or-tools/BuildTools/blob/master/coin.m4#L1928.

**Comment by svigerske** [comment]
Closing as no response and it works for me :).
