### ISSUE TITLE
CoinUtils should export whether it has GLPK or not

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#121]
CoinUtils doesn't currently export a symbol that indicates whether it is built with support for GMPL. If Cbc detects the presence of GLPK, but then happens to link to a version of CoinUtils previously built without support for GMPL, the linking fails (this just happened to me). It seems Cbc should not actually look for GLPK at all---it should just either look for OSI GLPK (in the case of CbcGeneric) or check to see whether CoinUtils has support for GLPK by checking `CoinUtilsConfig.h` for a symbol like COINUTILS_HAS_GLPK. If CoinUtils has support, then libcoinglpk should already be added to the link line by in `coinutils.pc`.

I guess we probably shouldn't have any symbols like `COIN_HAS_XXX`. They should all be `COINXYZ_HAS_XXX`. I recall we discussed something about this at some point (For example, we do use `OS_HAS_XXX` in the [OS configuration file](https://github.com/coin-or/OS/blob/master/OS/src/config_os.h.in). 

Right now, it seems that `COIN_HAS_XXX` is baked in to the macros in `coin.m4` but I guess it wouldn't be that difficult to change to `COINXYZ_HAS_XXX` (modifying `coin.m4` would be easy, but this would also require changes to individual projects). If this all sounds right, I can open a ticket in BuildTools (or we can transfer this one). In general, it would be nice to have this fixed, since it pretty often happens to me that building fails because some libraries that are already installed were built with different settings. I guess most users won't encounter this, but I did see someone reporting the same linking error with Glpk that I just had now.

**Comment by svigerske** [comment]
While `COINXYZ_HAS_ABC` would have been nicer, I'm not so much in mood to touch all the projects to adjust to this renaming.
There is now an additional `COINUTILS_HAS_GLPK`, which is exported in the API. Feel free to make use of it in Cbc.

Cbc needs to look for Glpk because it wants to include the glpk header and call some gmpl function. Surely it would have been better to encapsulate all Gmpl functionality in CoinUtils instead of having some global `cbc_glp_*` symbols in CoinUtils, but it's Cbc you talk about here...

**Comment by tkralphs** [comment]
I still don't see why Cbc would need to check for Glpk. If CoinUtils includes support for GMPL, then it must include the glpk header and any include directories needed should be in its `CFLAGS`, which Cbc gets, right? 

Anyway, Cbc should not be directly including `glpk.h`, it should include a CoinUtils header which includes `glpk.h`. If I get ambitious, maybe I will try to fix this.

What if we export both `COINXYZ_HAS_ABC` and `COIN_HAS_ABC` goinforward and try to slowly update the projects in the Cbc stack to conform? I'm going to start moving a bunch of other projects to the new build system and it seems silly not to do those in the "right" way while I'm at it.

**Comment by svigerske** [comment]
Well, ok, if we are ambitious and should improve on this anyway, then now is a good time to rename things. I have this in BuildTools (not pushed yet) and will go through those projects that I usually look at.
It will be `XYZ_HAS_ABC`, but only for things that our m4 macros define. There are autoconf standard macros that will still define a `HAVE_ABC`.

**Comment by svigerske** [comment]
So a lot of defines now have a different name, e.g., https://github.com/coin-or/CoinUtils/commit/a27aca41cd1d89c06e030989915fe71e63e5a69a#diff-d23f5b7090d56af546252d03336564a3

There was also an "API"-change in coin.m4, which means that you should remove the arguments from AC_COIN_INITIALIZE and AC_COIN_DEBUGLEVEL (if you use that): https://github.com/coin-or/CoinUtils/commit/a27aca41cd1d89c06e030989915fe71e63e5a69a#diff-67e997bcfdac55191033d57a16d1408a

**Comment by tkralphs** [comment]
This is BRILLIANT, THANKS!
