### ISSUE TITLE
conflict graph functions missing in API

### ISSUE THREAD

**Issue by svigerske** [coin-or/CoinUtils#122]
The new conflict graph stuff seems to miss exporting some of its classes in the API, so that Osi, Cgl, Cbc, etc fail to build: https://ci.appveyor.com/project/tkralphs/osi-s4knr/builds/31608633/job/n6tie3n6t4kajmi0

**Comment by h-g-s** [comment]
Hi @svigerske , thanks for checking it.  Sorry for the ignorance, but how do we solve it ???  I'm not familiar with the purpose and what to add in the exports.

**Comment by svigerske** [comment]
The purpose it to make the API functions accessible in libraries.

In CoinUtils, this happens by putting a COINUTILSLIB_EXPORT to the class or function declarations. We had done this for the previous conflict graph code, so I wonder how this could have disappeared.

Until some days ago, I could configure and build with this one in my config.site file:
```
case $PWD in
  *ThirdParty-Glpk* ) ;;
  *ThirdParty-ASL* ) ;;
  *ThirdParty-Metis* ) ;;
  *ThirdParty-Mumps* ) ;;
  *)
    ADD_CFLAGS="$ADD_CFLAGS -fvisibility=hidden"
    ADD_CXXFLAGS="$ADD_CXXFLAGS -fvisibility=hidden"
    ;;
esac
```
(essentially change default visibility to hidden for all except third-party codes, as they do not export their API properly)

**Comment by tkralphs** [comment]
I missed what the `-fvisibility=hidden` does exactly and why you are adding it yourself when we don't have it in the test builds? Also, I thought you said that we got rid of `ADD_*_FLAGS` in the new build system, so why would this have any effect for master builds?

**Comment by svigerske** [comment]
I have it in the [tests for Ipopt](https://github.com/coin-or/Ipopt/blob/master/.travis.yml#L52), but I leave it to you to setup the travis and appveyor for many other projects as you like.
I just mention it here as I find it an easy (since it doesn't need MSVC) first check whether the API export flags are set correctly.
I would have liked to just have a pragma that makes this a default in the code, but that didn't work easily for some reason I don't recall.

I had added the `ADD_*_FLAGS` back a while ago, essentially due to your wish back then.

**Comment by tkralphs** [comment]
So it `-fvisibility=hidden` basically simulates the export mechanism of `cl` using `gcc`?

**Comment by tkralphs** [comment]
Never mind, I now RTFM :).

**Comment by h-g-s** [comment]
Hi @svigerske ,  tried to add here but it is not compiling, I need also to add some include ?

for example:

class COINUTILSLIB_EXPORT CoinCliqueExtender {
public:
...
gives the error:

 CXX      CoinCliqueExtender.lo
In file included from CoinCliqueExtender.cpp:8:
CoinCliqueExtender.hpp:9:27: error: variable ‘COINUTILSLIB_EXPORT CoinCliqueExtender’ has initializer but incomplete type
    9 | class COINUTILSLIB_EXPORT CoinCliqueExtender {
      |                           ^~~~~~~~~~~~~~~~~~
CoinCliqueExtender.hpp:10:1: error: expected primary-expression before ‘public’
   10 | public:
      | ^~~~~~

**Comment by svigerske** [comment]
Sure, CoinUtilsConfig.h.

**Comment by svigerske** [comment]
Now that Osi is fine, please continue fixing up for the Cgl build:
https://ci.appveyor.com/project/tkralphs/cgl-e24vn/builds/31634308/job/gkhrodfpyks6xxgb

**Comment by svigerske** [comment]
This seems to have been fixed. Thanks.
