### ISSUE TITLE
CoinBronKerbosch doesn't compile unless C++ >= 11

### ISSUE THREAD

**Issue by svigerske** [coin-or/CoinUtils#123]
See, e.g., https://travis-ci.org/github/coin-or/CoinUtils/jobs/665188338

We have a compile-define COINUTILS_CPLUSPLUS11 that can be used to check whether C++11 is available.

**Comment by tkralphs** [comment]
As we've discussed, it's probably better to avoid using C++11 if possible, but if there are cases where it will really make a big performance difference, using `COINUTILS_CPLUSPLUS11` and having an alternative implementation might be OK.

**Comment by h-g-s** [comment]
Samuel rewrote the code in C++ 98. C++11 would not be enough for part of the code - partial_sort, that was used in other parts of the code requires C++ 17 ...
