### ISSUE TITLE
Unit test failure during installation

### ISSUE THREAD

**Issue by ShraddhaBG** [coin-or/CoinUtils#124]
Hi

I am trying to configure on Windows using MSYS2 (mingw64).
Steps to Configure, Build, Run and Install for Blas 1.4, Lapack 1.5 are completed.
There is an error in Running CoinUtils as follows. Any idea to solve this issue and move further? Thanks in advance.

##################################################

Running CoinUtils unit test
##################################################

Testing CoinFinite ... finite value: ok; infinite value: ok.
Testing CoinIsnan ... finite value: ok; NaN value: ok.
Testing CoinModel
Assertion failed: numErr== 0, file C:/MSYS64/home/DELL/coinbrew/CoinUtils/CoinUtils/test/CoinModelTest.cpp, line 447
make[1]: *** [Makefile:600: test] Error 3
make: *** [Makefile:819: test] Error 2

Build failed, see error output above

**Comment by svigerske** [comment]
Probably it is just missing the test data from https://github.com/coin-or-tools/Data-Sample
If you configure and install this first, and then reconfigure, rebuild, and retest CoinUtils, then it may work.

**Comment by tkralphs** [comment]
It does seem to be something with reading an MPS file, but the issue originally arose in the context of building Cbc, so the test data should be there. Maybe it's not linking libz, but also not unzipping the MPS files? Can you say exactly what steps you followed (what arguments to `coinbrew`, etc.) and attach config.log from `build/CoinUtils/master` (or whatever version you are building).

**Comment by ShraddhaBG** [comment]
I followed the Build and Install instructions on following link: https://github.com/coin-or/MibS,
And attached log file:
[config.log](https://github.com/coin-or/CoinUtils/files/4401790/config.log)

**Comment by svigerske** [comment]
https://github.com/coin-or/MibS/blob/master/Dependencies is missing Data/Sample and coinbrew doesn't do recursive dependency checks.

**Comment by tkralphs** [comment]
Ah, yes, makes sense. But shouldn't the unit test itself detect whether Data/Sample is present?

**Comment by svigerske** [comment]
Probably. At least it could stop with a better error message. You want to check that with Laci? ;)

**Comment by tkralphs** [comment]
Haha, yeah...

**Comment by tkralphs** [comment]
OK, this is now fixed in ddcf710daa1e3240e42bae0d1adee2a489736cae.
