### ISSUE TITLE
Error during installation (recompile with -fPIC)

### ISSUE THREAD

**Issue by FraCorti** [coin-or/CoinUtils#129]
Good morning, 

I'm trying to build CointUtils on my computer (Ubuntu 18.04 LTS) following the "Getting Started" written in the README but I get stuck with this error: 

![error](https://user-images.githubusercontent.com/34550805/79066089-511cfb00-7cb5-11ea-9483-40b5e668eb07.png)

I tried to install CoinUtils both ways: Expert users and using the script at https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew, and every time the error appears.

This happens even if I recompile all the files with the flag -fPIC (following the instruction given at this link https://stackoverflow.com/questions/23407635/append-compile-flags-to-cflags-and-cxxflags-while-configuration-make/23407800). 

I read on Gentoo Linux (https://wiki.gentoo.org/wiki/Project:AMD64/Fixing_-fPIC_Errors_Guide) that this can be a gcc bug.

Has this error happened to anyone during the installation? 
Did he/she solve this thing? 

Thanks for your reply and good holidays.

**Comment by svigerske** [comment]
Problem is that it tries to use a static libbz2 that hasn't been compiled with PIC to build a shared CoinUtils library. Either use `--disable-shared` or `--disable-bzlib` or install a bzlib that has been build with PIC enabled.

**Comment by FraCorti** [comment]
Thank you very much @svigerske
