### ISSUE TITLE
Configure script checks for a fortran compiler it doesn't need

### ISSUE THREAD

**Issue by orlitzky** [coin-or/CoinUtils#132]
This was reported to us in Gentoo at https://bugs.gentoo.org/601648 and still affects the latest version:

```
configure: Trying to determine Fortran compiler name
checking for gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
configure: Fortran compiler options are: -O3 -pipe  
checking how to get verbose linking output from gfortran... -v
checking for Fortran libraries of gfortran...  -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../.. -lgfortran -lm -lgcc_s -lquadmath
configure: Corrected Fortran libraries:  -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../.. -lgfortran -lm -lquadmath
checking for dummy main to link with Fortran libraries... none
checking for Fortran name-mangling scheme... lower case, underscore, no extra underscore
```

**Comment by svigerske** [comment]
The next major release will come with a larger update on the buildsystem, which also removes the check for a Fortran compiler.
I hesitate to touch the current stable version.

In the Gentoo bugreport it looks like x86_64-pc-linux-gnu-gfortran has been found, but is not usable. I guess there some reason for that, but you might want to try running configure with `F77=unavailable` as argument. Maybe that will trick CoinUtils to think that there is no Fortran compiler around, I'm not sure.

**Comment by orlitzky** [comment]
Ok, no problem. For now, I've required a working fortran compiler while building the Coin-OR stuff in Gentoo (I don't think it's a big deal for people who build math software). I left a pointer to this issue in our package, so we can check back from time to time to see if the build system has been overhauled.
