### ISSUE TITLE
Move from Travis and Bintray to Github Actions

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#153]
Bintray will shut down on May 1, so there is a need to move hosting for binaries. The preliminary idea is to move to attaching binaries as assets to releases, as is already being done for [Ipopt](https://github.com/coin-or/Ipopt). This seems like an opportune time to also consider moving from Travis to Github Actions, which provides more functionality.

**Comment by xmunoz** [comment]
How would you feel about leaving the windows build out of the Github Action's CI, @tkralphs? It looks like you already have AppVeyor configured for windows, so I'm not sure how much a windows build in GH Actions would add.

**Comment by tkralphs** [comment]
I don't know exactly how Github Actions works with Windows. It would be very nice not to have to deal with Appveyor anymore, but I'm willing to do that, at least in the short run, if it looks as though Github Actions won't provide the same abilities and range of available platforms/compilers. 

On Appveyor, we're not using a complicated setup, just using Msys2 + a few packages + Visual Studio. I would think it should be doable to simply install all but Visual Studio from scratch. Actually, once we have a conda build working for Windows (which I think it is reasonable to expect we will), then I would think that would work on Github Actions with Windows. 

But sure, for now, we can leave Appveyor as it is, as long as we can upload the binaries to Github.

**Comment by xmunoz** [comment]
For reference, here is what is supported for Windows on Github Actions:

- [Windows 2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md)
- [Windows 2016](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md)

If we decide we want to add it later, it would definitely be possible, but maybe slightly less urgent than getting off of Bintray.

**Comment by xmunoz** [comment]
Filename: {reposname}-{tag}-{osname+version}-{build_static[true|false]}-{plaform[x64|x86]}-{compiler}.tar.gz

**Comment by xmunoz** [comment]
TODO: Turn on address sanitizer (ASAN flag) for release binaries.

**Comment by xmunoz** [comment]
To package binary, add:
- everything in CoinUtils/dist/
- README, LICENSE

**Comment by xmunoz** [comment]
I just removed the Travis Webhook in the repository settings. This will need to be done for every repository that we migrate to Github Actions

**Comment by xmunoz** [comment]
#161 was the last required PR to get this working. Now all that is needed is to test it.

**Comment by tkralphs** [comment]
Hmm, testing, yes. Our current workflow is to make releases from `stable/*`, so there's a bit of prep work to be done to make that happen and our release procedures themselves are not well-tested on Github. We had a bunch of automations for making releases on SVN and there are newer scripts now for doing the same on Github, but they haven't gotten much use. 

Putting all that aside, we also first need to get all this working in `stable/2.11`. It's not perfectly clear to me what needs to be done to make that happen. Is it enough just to add the contents of `.github/workflows` to `stable/2.11`?

**Comment by xmunoz** [comment]
I recommend moving over `appveyor.yml` and `.github/`, as well as removing all files related to travis. Also, you don't need to do a real release. You can just push a tag on master and see if it works. It's easy to remove tags and releases.

**Comment by tkralphs** [comment]
OK, I just pushed a test tag and all seems good!

**Comment by xmunoz** [comment]
Cool! So there is one more step. You'll notice that the release was created as me, because the action is using my token. I wanted to test it this way first to make sure the permissions for the token were correct, but it looks like they are so we should probably move to a token owned by you. Go [here](https://github.com/settings/tokens/new) and create a Personal Access token. These are the permissions it needs.

![Captura de pantalla de 2021-04-28 13-25-12](https://user-images.githubusercontent.com/1065196/116800253-1e62c200-aac5-11eb-8956-c1feb3792f1d.png)

Then add the token as a organization secret. The reason for adding it to the org is that we will probably be reusing this setup in a lot of repositories. Once all that is done, send a PR to the CI workflow changing the reference from `XMUNOZ_PAT` to whatever you named your organization secret.

**Comment by tkralphs** [comment]
OK, done, see #164 .
