### ISSUE TITLE
Appveyor CI is painfully slow

### ISSUE THREAD

**Issue by xmunoz** [coin-or/CoinUtils#158]
I've open a few PRs to this repository now and I've noticed that it often takes hours for the AppVeyor builds to complete. Upon further investigation, I've identified the following inefficiencies:

- Builds are sequential, with each platform taking 6-10 minutes to complete
- There are a large number of builds (10), including for platforms that are now 6 years old and deprecated by Microsoft
  - This means that every commit takes over an hour for a full build to complete
- Fast fail is not configured, so builds will continue even if one fails
-  "Rolling builds" option is not enabled, meaning that the queue fills up with old commits, and will build for every single one, even if there are newer commits.

Most of these options are configurable in the `appveyor.yml` file, but I believe the last on is only changeable through the UI. @tkralphs can you grant me access to the COIN-OR project on appveyor? I'd like to see what other configuration options are available. For the rest of these issues, I'll send a PR.

**Comment by xmunoz** [comment]
Another inefficiency: Build occurs on pushes to every branch and every open PR, meaning two builds are queued up every time I push to a branch that is in an open PR. We should probably only build on:
- Pushes to master
- Pushes to open PRs to master

**Comment by xmunoz** [comment]
@tkralphs you were right. It doesn't look like there is anything we can do about the parallel builds:

> In some scenarios it is useful to split tests into jobs on the Free plan as well, but jobs will run in series as the Free plan allows 1 concurrent job per account.

https://www.appveyor.com/docs/parallel-testing/

**Comment by tkralphs** [comment]
Oh well :(. I think we may be able to move to Github Actions eventually. For now, it's fine. 

I see what you mean now about pushing to a branch that is an open PR. That just isn't something we usually do in our current workflow (although we should) and you would think Appveyor would have an option to deal with that. It is pretty important to build on pushes to stable branches, so I'm not sure if there is anything to do beyond disabling builds on branches we know are open PRs. Or we can just live with the fact that it's incredibly slow, which is what we've done for years. At least we haven't gotten to the tipping point where we can't ever catch up :).

**Comment by xmunoz** [comment]
Just enabled "Rolling Builds" in the AppVeyor UI. We should see a significant speed-up with this alone.

https://www.appveyor.com/docs/build-configuration/#rolling-builds

**Comment by xmunoz** [comment]
Updated the Appveyor webhook to just respond to push events (e.g. pushing to branches). This eliminates the duplicate build problem on PRs.

**Comment by tkralphs** [comment]
Right, but if the PR is from a fork, we do want the build to be triggered. Is there a setting to only trigger PR builds from forks? That seems like something one might obviously want.

**Comment by xmunoz** [comment]
Ref: https://github.com/appveyor/ci/issues/882

I'll re-add the webhook but add `skip_branch_with_pr: true` to the Appveyor yaml.

**Comment by tkralphs** [comment]
Nice!
