### ISSUE TITLE
ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021

### ISSUE THREAD

**Issue by xmunoz** [coin-or/CoinUtils#171]
Currently the linux builds have this warning in github actions. Before we roll out this configuration to other repos, I'd like to confirm what the deprecation plan is for the ubuntu-16.04 build. Remove it now? Wait until September?

**Comment by svigerske** [comment]
I am not aware of plans, but I vote for dropping it. Ubuntu 16.04 is no longer supported by Ubuntu since this month, so moving on to 18.04 sounds good to me.

**Comment by tkralphs** [comment]
I'm OK with removing it.
