### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by xmunoz** [coin-or/CoinUtils#172]
I have scoured the documentation and haven't found an explicitly-articulated code of conduct. This would be a good thing to do in general, and specifically would help us grow the COIN-OR community and apply for funding.

I recommend the [Contributor Covenant](https://www.contributor-covenant.org/).

The exit criteria for this issue: Adopt a code of conduct for this repository and this organization, and identify an email address where users can report violations.

**Comment by tkralphs** [comment]
This was discussed by the board of the COIN-OR Foundation and we agreed in principle to adopt the recommended code of conduct not just for this repository but for all COIN-OR repositories. The details of exactly how to implement this are being sorted out. A little more research is needed into the mechanisms we need to have in place for reporting, etc.

**Comment by xmunoz** [comment]
I created [this discussion](https://github.com/coin-or/COIN-OR-OptimizationSuite/discussions/16) and cross-posted on the coin-discuss mailing list.

**Comment by xmunoz** [comment]
@tkralphs and I had a discussion about next steps this afternoon:
1) @tkralphs to create a wordpress account for cristina@coin-or.org
2) I'll create a draft page with a new code of conduct, and get approval before publishing the draft
3) @tkralphs to set up a google groups mailing list (with conversation history turned off) for CoC violation reports (perhaps conduct@coin-or.org, or something similar)
4) I'll open up PRs to the various repositories in the coin-or organization that link to the new CoC in the README

The goal is to get all of this rolled out by the week of June 14.

**Comment by tkralphs** [comment]
1 and 3 above are done. The e-mail address for the Google group is code-of-conduct@coin-or.org.

**Comment by xmunoz** [comment]
2 is not done because I was moving apartments all last week, but I'll definitely get to it in the next few days.

**Comment by xmunoz** [comment]
Welp, I started a new job and this has taken a little longer than anticipated, but we have a CoC: https://www.coin-or.org/code-of-conduct/

And a mailing list: code-of-conduct@coin-or.org. Now we just need to add links to the READMEs, via coinbrew or manually.
