### ISSUE TITLE
CoinUtils fails to read valid MPS file

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#206]
CoinUtils fails to read the attached MPS file. I can't seem to replicate the issue with any other file. The failure is on the last line of the file, which happens not to have a carriage return. When reading the last line of the file, on this line here:
https://github.com/coin-or/CoinUtils/blob/cdd05b79a549c06a8a4ebc09a3e45a6d08522a95/CoinUtils/src/CoinFileIO.cpp#L146
`initiallyEmpty` is set to `true` when it should `false` but I can't see exactly why. Then `getIt` is `false` here
https://github.com/coin-or/CoinUtils/blob/cdd05b79a549c06a8a4ebc09a3e45a6d08522a95/CoinUtils/src/CoinMpsIO.cpp#L282
and finally `cleanCard()` returns `true` here:
https://github.com/coin-or/CoinUtils/blob/cdd05b79a549c06a8a4ebc09a3e45a6d08522a95/CoinUtils/src/CoinMpsIO.cpp#L511
but since the section is never updated to `COIN_ENDDATA_SECTION`, it looks as though the file has ended without reaching `ENDDATA` even though this isn't the case. 

I can't quite see why this is happening. I thought it has something to do with the missing carriage return, but If I unzip the file, it works fine even without adding a carriage return. If I add a carriage return and rezip, it's also fine. So I give up. @jjhforrest any idea?
[OR5x500-0.25_9.dat-50.mps.gz](https://github.com/coin-or/CoinUtils/files/11124394/OR5x500-0.25_9.dat-50.mps.gz)

**Comment by jjhforrest** [comment]
Odd - but easy to get round

code returns a count of 6 i.e. ENDATA with no terminating character.  There is a check for terminating character or end of buffer so the following fixes problem and does no harm.

```
-- a/src/CoinFileIO.cpp
+++ b/src/CoinFileIO.cpp
@@ -176,6 +176,9 @@ public:
           // return 0, otherwise at least the buffer contents were
           // transfered and buffer has to be returned.
           return initiallyEmpty ? 0 : buffer;
+       } else {
+         // in case image does not terminate as expected
+         destLast = dest + count-1;
         }
```
If you want I (or you can) can check modification into stable and master

**Comment by tkralphs** [comment]
I haven't tried to run this through a debugger to see what it's doing, but I would think the fix would be to make it so that `initiallyEmpty` is actually set to the correct value. Is that difficult to do? Otherwise, the value of that variable can't actually be trusted and then we shouldn't use it at all. Offhand, it looks to me like the code is meant to fall into `if` block if the end of the file is reached and then it will always return the wrong value if `initallyEmpty` is not set correctly. Maybe I'm missing something.

**Comment by jjhforrest** [comment]
That won't work
you don't want to return 0 and you don't want to return buffer as it was ENDATAxxxxxx with no immediate \0 or \n
          return initiallyEmpty ? 0 : buffer;
The fix I suggested works - but feel free to run it through a debugger

**Comment by tkralphs** [comment]
Hmm, OK, but why does the string have the garbage appended to it anyway? Shouldn't buffer by \0 terminated if end of file is reached? I guess it's because the file is being read directly from gzipped format or something? Anyway, you know better than me, feel free to commit.

**Comment by jjhforrest** [comment]
I think it is a minor bug/feature of the code which deals with gzipped files (gzread).  This is what we get -

Thread 1 "cbc" hit Breakpoint 12, CoinGetslessFileInput::gets (this=0x555555ed36b0, buffer=0x555555f268e8 "ENDATAound  y499  1.0000000", size=880) at /home/john/cbctemp/CoinUtils/src/CoinFileIO.cpp:190

as you can see the buffer is the previous entry with 6 characters replaced but no \0.  However count is 6 which tells us enough.
It is a minor bug and won't affect any real application.  I will commit just to master for now.

**Comment by tkralphs** [comment]
Thanks! I tested and cherry picked over the stable/2.11, since I need it there.
