### ISSUE TITLE
Error parsing an MPS file

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#208]
When reading the instance attached below with `readMps()`, I get the error message
```
Coin3006W No match for column 0 at line 813 <  LI bound x0 0 >
Coin3006W No match for column 1 at line 814 <  UI bound x0 1 >
```
At first, I thought it was another bug in the parsing of the gzipped file, but the same thing happens when unzipping. It looks like it is getting the column name as `boundx0` instead of `x0` for some reason, but I didn't dig too deep on this one. @jjhforrest, can you help?

[interKP-100-100-9-4.mps.gz](https://github.com/coin-or/CoinUtils/files/11187304/interKP-100-100-9-4.mps.gz)

**Comment by jjhforrest** [comment]
It works on master, but the mps file is actually in error as it should have FREE on NAME image.  The code in master is more forgiving and sees the line is too short and changes to free format.

**Comment by tkralphs** [comment]
OK, thanks, cherry picking 4bcac59d fixes the issue. So you see any problem with patching stable/2.11 with that commit?

**Comment by tkralphs** [comment]
See 793eda8.
