### ISSUE TITLE
configure script has issue when pwd contains spaces

### ISSUE THREAD

**Issue by svigerske** [coin-or/CoinUtils#87]
Issue created by migration from Trac.

Original creator: alcinos

Original creation time: 2017-11-06 13:37:42

Version: 

Keywords: configure

See attached a patch for a tentative fix (probably incomplete)

**Comment by svigerske** [comment]
Attachment [fix_path.patch](https://www.coin-or.org/issue-attachments/CoinUtils/ticket87/fix_path.patch) by alcinos created at 2017-11-06 13:38:44

patch

**Comment by svigerske** [comment]
We're not supported spaces in paths for the moment. One small patch will not fix this.

**Comment by Mizux** [comment]
this is related to GNU/Make which doesn't support space in path 
see https://savannah.gnu.org/bugs/?712

note: CMake based build should support space in path (working on it)
related to https://github.com/google/or-tools/issues/801
