### ISSUE TITLE
CoinPackedMatrix - how to set minorDim_

### ISSUE THREAD

**Issue by kingaj12** [coin-or/CoinUtils#91]
I am building a CoinPackedMatrix element by element.  I am using the following template:

    cpm = std::make_shared<CoinPackedMatrix>();
    cpm->reserve(ncols, nnz, true);
    // … snip … //
    cpm->modifyCoefficient(rowIndx, colIndx, value);
    n = cpm->getNumElements(); // = 0

The documentation seems to indicate that `cpm->reserve()` will create appropriate arrays, and `cpm->modifyCoefficient()` will insert/modify values as needed.  But it doesn't seem to, and the problem is that `minorDim_` is zero.  Did I miss something?

Now, I could build the (`rowIndx, colIndx, value)` arrays and load them into a CPM, but it would be nice if I could encapsulate things this way.  What would be the preferred template?

**Comment by svigerske** [comment]
I believe that `reserve()` only reserves space, but doesn't change dimension. `setDimensions()` should probably be called.
