### ISSUE TITLE
Doesn't link to glpk

### ISSUE THREAD

**Issue by yurivict** [coin-or/CoinUtils#92]
I am setting ```--with-glpk-incdir="${LOCALBASE}/include" --with-glpk-lib="${LOCALBASE}/lib/libglpk.so"``` but resulting binaries aren't linked with ```libglpk.so```.

**Comment by svigerske** [comment]
It would be good to see output of configure, which should show whether Glpk was recognized.

**Comment by svigerske** [comment]
Maybe try again with current trunk/master (much has changed).
